### ISSUE TITLE
Wrong JDK & Incorrect Step #4 in Microservices script

### ISSUE THREAD

**Issue by scxbush** [mavogel/vis-lab#8]
I'm a big fan of this project as it really shows what many organizations are doing by converting their legacy webapps into microservices.  Just spent the last 3 days debugging and getting this to run & I'd  love to make a pull request.  I created ps1 scripts for the .sh files so that this can be run on Windows, updated the jdk since the last one is no longer on docker hub, and changed how the docker build works for legacywebshop_micro.

**Comment by mavogel** [comment]
Hey, @scxbush sounds awesome. There was no windows support yet. Please make a PR and I can help you set it up. Which jdk is not available anymore?

**Comment by scxbush** [comment]
I updated the jdk in line 104 in the main pom.xml file to the following:
<build>
<from>frolvlad/alpine-java:jdk8-slim</from>
<tags>
<tag>latest</tag>
</tags>

Just tried to do a pull request to the repo and got:
remote: Permission to mavogel/vis-lab.git denied to scxbush.

**Comment by mavogel** [comment]
> Just tried to do a pull request to the repo and got:
remote: Permission to mavogel/vis-lab.git denied to scxbush.

That's fine. You need to [fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) it firt and then make a Pull Request :)
